name: Deploy to Cloud Run

on:
  push:
    branches:
      - master  # or 'main', whichever your repo uses

jobs:
  deploy-to-cloud-run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      # 1) Install the gcloud CLI (but do not pass credentials here)
      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: beta  # or specify other components if needed

      # 2) Authenticate with Google (service account JSON key)
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 3) Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy my-viz-service \
            --image=docker.io/guenpa92/viz:latest \
            --platform=managed \
            --region=us-central1 \
            --allow-unauthenticated
