name: Deploy to Cloud Run

on:
  push:
    branches:
      - master  # Deploy when you push to the 'main' branch

jobs:
  deploy-to-cloud-run:
    runs-on: ubuntu-latest
    steps:
      # 1) Check out the repo (so Actions can access it)
      - name: Check out code
        uses: actions/checkout@v3

      # 2) Set up the Google Cloud SDK, using your secrets for auth
      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      # 3) Deploy to Cloud Run using your DockerHub image
      - name: Deploy to Cloud Run
        run: |
          # The name 'my-viz-service' can be anything; pick a relevant name
          gcloud run deploy my-viz-service \
            --image=docker.io/guenpa92/viz:latest \
            --platform=managed \
            --region=us-central1 \
            --allow-unauthenticated